### ISSUE TITLE
Make a wiki page for v86 testers.

### ISSUE THREAD

**Issue by UniqueName12345** [Orange-OS-LE/CLI_Installer#11]
The instructions all require you to access "curl" and, by extension, the internet. When I tried to do that...

I get a error stating:

`v86_username@localhost:~# curl https://raw.githubusercontent.com/Orange-OS-LE/CLI_Installer/master/script_part_1.py > install.py` <- my command

` % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: raw.githubusercontent.com` <- the errror

Can someone make the wiki have a page titled something like "For v86 users"?

**Comment by michaeleldar** [comment]
How do you know this is something to do with v86. It just looks like you can't connect to the internet.

**Comment by UniqueName12345** [comment]
> How do you know this is something to do with v86. It just looks like you can't connect to the internet.

I tried what they said, and I just can not get internet access to work on v86, so...

**Comment by michaeleldar** [comment]
Well you can make a wiki page then
